services:
  server:
    image: ghcr.io/m8ke/aircloud/server:${AIRCLOUD_VERSION:-latest}
    restart: unless-stopped
    container_name: aircloud-server
    environment:
      PORT: ${SERVER_PORT:-8000}
      DOMAIN: ${DOMAIN:-aircloud.sh}
      JWT_SECRET: ${JWT_SECRET}
      TURN_SECRET: ${TURN_SECRET}
      STUN_IP: stun:${DOMAIN:-turn.aircloud.sh}:3478  # optional
      TURN_IP: turns:${DOMAIN:-turn.aircloud.sh}:5349 # optional
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"

  client:
    image: ghcr.io/m8ke/aircloud/client:${AIRCLOUD_VERSION:-latest}
    restart: unless-stopped
    container_name: aircloud-client
    environment:
      PORT: ${CLIENT_PORT:-4000}
    ports:
      - "${CLIENT_PORT:-4000}:${CLIENT_PORT:-4000}"
    depends_on:
      - server
