services:
  server:
    image: ghcr.io/${GH_REPOSITORY}/server:latest
    restart: unless-stopped
    container_name: server
    build:
      context: ./server
    environment:
      PORT: ${SERVER_PORT}
      DOMAIN: ${DOMAIN}
      TURN_SECRET: ${TURN_SECRET}
      STUN_IP: ${STUN_IP}
      TURN_IP: ${TURN_IP}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    image: ghcr.io/${GH_REPOSITORY}/client:latest
    restart: unless-stopped
    container_name: client
    build:
      context: ./client
    environment:
      PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - server
