aircloud:
  jwt:
    secret: ${JWT_SECRET}
  cors:
    origin: https://${DOMAIN}
  turn:
    secret: ${TURN_SECRET}
    stun-ip: ${STUN_IP}
    turn-ip: ${TURN_IP}

spring:
  application:
    name: AirCloud

server:
  port: ${PORT}
  forward-headers-strategy: native
