aircloud:
  jwt:
    secret: super-secret-123-asd
  cors:
    origin: "*"
  turn:
    secret: secret-only-for-development
    stun-ip: stun:127.0.0.1:3478
    turn-ip: turn:127.0.0.1:3478

spring:
  application:
    name: AirCloud

server:
  port: 8080
