export enum SocketResponseType {
    CONNECT = "CONNECT",
    DISCONNECT = "DISCONNECT",
    PING_PONG = "PING_PONG",
    OFFER = "OFFER",
    ANSWER = "ANSWER",
    APPROVE_ANSWER = "APPROVE_ANSWER",
    PEER_CONNECT = "PEER_CONNECT",
    ICE_CANDIDATE = "ICE_CANDIDATE",
    END_OF_ICE_CANDIDATES = "END_OF_ICE_CANDIDATES",
}
