export enum SocketRequestType {
    CONNECT = "CONNECT",
    OFFER = "OFFER",
    ANSWER = "ANSWER",
    PEER_CONNECT = "PEER_CONNECT",
    PEER_RECONNECT = "PEER_RECONNECT",
    ICE_CANDIDATE = "ICE_CANDIDATE",
    END_OF_ICE_CANDIDATES = "END_OF_ICE_CANDIDATES"
}
